# Generated by Django 3.0.8 on 2020-07-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.BooleanField(verbose_name='是否该标的原研')),
                ('bid_price', models.FloatField(verbose_name='报价')),
                ('original_price', models.FloatField(blank=True, null=True, verbose_name='集采前最低价')),
            ],
            options={
                'verbose_name': '投标记录',
                'verbose_name_plural': '投标记录',
                'ordering': ['-bid_price'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='企业名称')),
                ('mnc_or_local', models.BooleanField(verbose_name='是否跨国企业')),
            ],
            options={
                'verbose_name': '制药企业',
                'verbose_name_plural': '制药企业',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=30, verbose_name='带量品种')),
                ('vol', models.CharField(max_length=30, verbose_name='批次')),
                ('tender_begin', models.DateField(verbose_name='标期起始日期')),
                ('bidder_num', models.IntegerField(verbose_name='竞标者数量')),
            ],
            options={
                'verbose_name': '集采标的',
                'verbose_name_plural': '集采标的',
                'ordering': ['target'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('上海', '上海'), ('重庆', '重庆'), ('广州', '广州'), ('深圳', '深圳'), ('成都', '成都'), ('沈阳', '沈阳'), ('大连', '大连'), ('西安', '西安'), ('厦门', '厦门'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆（含兵团）', '新疆（含兵团）')], max_length=10, verbose_name='区域')),
                ('spec', models.CharField(max_length=10, verbose_name='规格')),
                ('amount_reported', models.FloatField(verbose_name='报量')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbp.Tender', verbose_name='标的')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vbp.Bid', verbose_name='中标供应商')),
            ],
            options={
                'verbose_name': '地方报量',
                'verbose_name_plural': '地方报量',
                'ordering': ['tender', 'region', 'spec'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbp.Company', verbose_name='竞标厂商'),
        ),
        migrations.AddField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbp.Tender', verbose_name='所属记录'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('tender', 'bidder')},
        ),
    ]
