# Generated by Django 3.0.8 on 2020-07-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tender',
            unique_together={('target', 'vol')},
        ),
    ]
