# Generated by Django 3.0.8 on 2020-07-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0002_auto_20200722_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='amount_reported',
        ),
        migrations.AddField(
            model_name='volume',
            name='amount_contract',
            field=models.FloatField(default=0, verbose_name='合同量'),
            preserve_default=False,
        ),
    ]
