# Generated by Django 3.0.8 on 2021-02-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0007_auto_20200824_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_spec',
            field=models.CharField(default='', max_length=30, verbose_name='报价规格'),
            preserve_default=False,
        ),
    ]
