# Generated by Django 3.0.8 on 2021-02-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0009_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='文件名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='vol',
            field=models.CharField(default='', max_length=30, verbose_name='批次'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(upload_to='doc_files/%Y/%m/%d/', verbose_name='PDF文件'),
        ),
    ]
